// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ContestCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at'],
    title: 'ContestCreate'
} as const;

export const ContestProblemsCreateSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id'],
    title: 'ContestProblemsCreate'
} as const;

export const ContestProblemsPublicSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id', 'id'],
    title: 'ContestProblemsPublic'
} as const;

export const ContestProblemsUpdateSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id'],
    title: 'ContestProblemsUpdate'
} as const;

export const ContestPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        problem_links: {
            items: {
                '$ref': '#/components/schemas/ContestProblemsPublic'
            },
            type: 'array',
            title: 'Problem Links',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at', 'id'],
    title: 'ContestPublic'
} as const;

export const ContestUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at'],
    title: 'ContestUpdate'
} as const;

export const ContestsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ContestPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ContestsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        login_id: {
            type: 'string',
            title: 'Login Id'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['login_id', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProblemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        time_limit: {
            type: 'string',
            title: 'Time Limit'
        },
        memory_limit: {
            type: 'integer',
            title: 'Memory Limit'
        },
        content: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Content'
        },
        input_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Input Format'
        },
        output_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Output Format'
        },
        samples: {
            items: {
                '$ref': '#/components/schemas/TestCaseSample'
            },
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Samples'
        }
    },
    type: 'object',
    required: ['name', 'time_limit', 'memory_limit', 'content', 'input_format', 'output_format', 'samples'],
    title: 'ProblemCreate'
} as const;

export const ProblemPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        time_limit: {
            type: 'string',
            title: 'Time Limit'
        },
        memory_limit: {
            type: 'integer',
            title: 'Memory Limit'
        },
        content: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Content'
        },
        input_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Input Format'
        },
        output_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Output Format'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        samples: {
            items: {
                '$ref': '#/components/schemas/TestCaseSample'
            },
            type: 'array',
            title: 'Samples'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'time_limit', 'memory_limit', 'content', 'input_format', 'output_format', 'id', 'samples'],
    title: 'ProblemPublic'
} as const;

export const ProblemUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        time_limit: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Limit'
        },
        memory_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Limit'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        input_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Format'
        },
        output_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Format'
        },
        samples: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/TestCaseSample'
                    },
                    type: 'array',
                    maxItems: 3,
                    minItems: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Samples'
        }
    },
    type: 'object',
    title: 'ProblemUpdate'
} as const;

export const ProblemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProblemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProblemsPublic'
} as const;

export const TestCaseSampleSchema = {
    properties: {
        input: {
            type: 'string',
            title: 'Input'
        },
        output: {
            type: 'string',
            title: 'Output'
        }
    },
    type: 'object',
    required: ['input', 'output'],
    title: 'TestCaseSample'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['login_id', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['login_id', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['login_id', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        login_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        login_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Id'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;