// This file is auto-generated by @hey-api/openapi-ts

export const AIBattleCreateSchema = {
    properties: {
        contest_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contest Id'
        },
        user_submission_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Submission Id'
        },
        models: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 3,
            minItems: 1,
            title: 'Models'
        }
    },
    type: 'object',
    required: ['user_submission_id', 'models'],
    title: 'AIBattleCreate'
} as const;

export const AIBattleGeneratedCodeCreateSchema = {
    properties: {
        participant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Participant Id'
        },
        model_id: {
            type: 'string',
            maxLength: 255,
            title: 'Model Id'
        },
        source_code: {
            type: 'string',
            minLength: 1,
            title: 'Source Code'
        },
        finish_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finish Reason'
        },
        usage: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Usage'
        }
    },
    type: 'object',
    required: ['participant_id', 'model_id', 'source_code'],
    title: 'AIBattleGeneratedCodeCreate'
} as const;

export const AIBattleParticipantPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        battle_id: {
            type: 'string',
            format: 'uuid',
            title: 'Battle Id'
        },
        participant_type: {
            type: 'string',
            title: 'Participant Type'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        model_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Id'
        },
        submission_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submission Id'
        },
        generation_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generation Status'
        },
        generation_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Generation Error'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num'
        }
    },
    type: 'object',
    required: ['id', 'battle_id', 'participant_type', 'display_name', 'order_num'],
    title: 'AIBattleParticipantPublic'
} as const;

export const AIBattlePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contest Id'
        },
        user_submission_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Submission Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        participants: {
            items: {
                '$ref': '#/components/schemas/AIBattleParticipantPublic'
            },
            type: 'array',
            title: 'Participants',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'problem_id', 'user_submission_id', 'status'],
    title: 'AIBattlePublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ContestCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at'],
    title: 'ContestCreate'
} as const;

export const ContestProblemsCreateSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id'],
    title: 'ContestProblemsCreate'
} as const;

export const ContestProblemsListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ContestProblemsPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ContestProblemsListPublic'
} as const;

export const ContestProblemsPublicSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        problem: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProblemMinimal'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id', 'id'],
    title: 'ContestProblemsPublic'
} as const;

export const ContestProblemsUpdateSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            type: 'string',
            format: 'uuid',
            title: 'Contest Id'
        },
        order_num: {
            type: 'integer',
            title: 'Order Num',
            default: 0
        }
    },
    type: 'object',
    required: ['problem_id', 'contest_id'],
    title: 'ContestProblemsUpdate'
} as const;

export const ContestPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        problem_links: {
            items: {
                '$ref': '#/components/schemas/ContestProblemsPublic'
            },
            type: 'array',
            title: 'Problem Links',
            default: []
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at', 'id'],
    title: 'ContestPublic'
} as const;

export const ContestSummariesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ContestSummaryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        server_now: {
            type: 'string',
            format: 'date-time',
            title: 'Server Now'
        }
    },
    type: 'object',
    required: ['data', 'count', 'server_now'],
    title: 'ContestSummariesPublic'
} as const;

export const ContestSummaryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        start_at: {
            type: 'string',
            format: 'date-time',
            title: 'Start At'
        },
        end_at: {
            type: 'string',
            format: 'date-time',
            title: 'End At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'start_at', 'end_at'],
    title: 'ContestSummaryPublic'
} as const;

export const ContestUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        start_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start At'
        },
        end_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End At'
        }
    },
    type: 'object',
    required: ['title', 'start_at', 'end_at'],
    title: 'ContestUpdate'
} as const;

export const ContestsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ContestPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ContestsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        login_id: {
            type: 'string',
            title: 'Login Id'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['login_id', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProblemCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        time_limit: {
            type: 'number',
            maximum: 2000,
            exclusiveMinimum: 0,
            title: 'Time Limit'
        },
        memory_limit: {
            type: 'integer',
            title: 'Memory Limit'
        },
        content: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Content'
        },
        input_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Input Format'
        },
        output_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Output Format'
        },
        samples: {
            items: {
                '$ref': '#/components/schemas/TestCaseSample'
            },
            type: 'array',
            maxItems: 3,
            minItems: 3,
            title: 'Samples'
        }
    },
    type: 'object',
    required: ['name', 'time_limit', 'memory_limit', 'content', 'input_format', 'output_format', 'samples'],
    title: 'ProblemCreate'
} as const;

export const ProblemMinimalSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        time_limit: {
            type: 'number',
            title: 'Time Limit'
        },
        memory_limit: {
            type: 'integer',
            title: 'Memory Limit'
        }
    },
    type: 'object',
    required: ['id', 'name', 'time_limit', 'memory_limit'],
    title: 'ProblemMinimal'
} as const;

export const ProblemPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        time_limit: {
            type: 'number',
            maximum: 2000,
            exclusiveMinimum: 0,
            title: 'Time Limit'
        },
        memory_limit: {
            type: 'integer',
            title: 'Memory Limit'
        },
        content: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Content'
        },
        input_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Input Format'
        },
        output_format: {
            type: 'string',
            maxLength: 1000,
            minLength: 1,
            title: 'Output Format'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        samples: {
            items: {
                '$ref': '#/components/schemas/TestCaseSample'
            },
            type: 'array',
            title: 'Samples'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'time_limit', 'memory_limit', 'content', 'input_format', 'output_format', 'id', 'samples'],
    title: 'ProblemPublic'
} as const;

export const ProblemUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        time_limit: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 2000,
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Limit'
        },
        memory_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Limit'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        input_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Format'
        },
        output_format: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Output Format'
        },
        samples: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/TestCaseSample'
                    },
                    type: 'array',
                    maxItems: 3,
                    minItems: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Samples'
        }
    },
    type: 'object',
    title: 'ProblemUpdate'
} as const;

export const ProblemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProblemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProblemsPublic'
} as const;

export const SubmissionCaseResultPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        case_index: {
            type: 'integer',
            title: 'Case Index'
        },
        verdict: {
            type: 'string',
            title: 'Verdict'
        },
        time_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Ms'
        },
        memory_kb: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Kb'
        },
        stdout_preview: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stdout Preview'
        },
        stderr_preview: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stderr Preview'
        },
        build_stderr_preview: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Build Stderr Preview'
        },
        exit_code: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Exit Code'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'case_index', 'verdict'],
    title: 'SubmissionCaseResultPublic'
} as const;

export const SubmissionCreateSchema = {
    properties: {
        language: {
            type: 'string',
            maxLength: 50,
            title: 'Language'
        },
        source_code: {
            type: 'string',
            minLength: 1,
            title: 'Source Code'
        },
        contest_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contest Id'
        }
    },
    type: 'object',
    required: ['language', 'source_code'],
    title: 'SubmissionCreate'
} as const;

export const SubmissionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        contest_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contest Id'
        },
        participant_type: {
            type: 'string',
            title: 'Participant Type'
        },
        ai_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Model'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        source_code: {
            type: 'string',
            title: 'Source Code'
        },
        verdict: {
            type: 'string',
            title: 'Verdict'
        },
        total_time_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Time Ms'
        },
        peak_memory_kb: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Peak Memory Kb'
        },
        code_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code Bytes'
        },
        physical_lines: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Physical Lines'
        },
        effective_lines: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Effective Lines'
        },
        max_nesting_depth: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Nesting Depth'
        },
        analysis_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Analysis Error'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        case_results: {
            items: {
                '$ref': '#/components/schemas/SubmissionCaseResultPublic'
            },
            type: 'array',
            title: 'Case Results',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'problem_id', 'participant_type', 'language', 'source_code', 'verdict'],
    title: 'SubmissionPublic'
} as const;

export const SubmissionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SubmissionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SubmissionsPublic'
} as const;

export const TestCaseSampleSchema = {
    properties: {
        input: {
            type: 'string',
            title: 'Input'
        },
        output: {
            type: 'string',
            title: 'Output'
        }
    },
    type: 'object',
    required: ['input', 'output'],
    title: 'TestCaseSample'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnlockStatusPublicSchema = {
    properties: {
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        ac_count: {
            type: 'integer',
            title: 'Ac Count'
        },
        unlocked: {
            type: 'boolean',
            title: 'Unlocked'
        }
    },
    type: 'object',
    required: ['problem_id', 'ac_count', 'unlocked'],
    title: 'UnlockStatusPublic'
} as const;

export const UserCreateSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['login_id', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['login_id', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        login_id: {
            type: 'string',
            maxLength: 255,
            title: 'Login Id'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['login_id', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        login_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Id'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;