// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ContestProblemsCreateContestProblemsData, ContestProblemsCreateContestProblemsResponse, ContestProblemsUpdateContestProblemsData, ContestProblemsUpdateContestProblemsResponse, ContestProblemsDeleteContestProblemsData, ContestProblemsDeleteContestProblemsResponse, ContestsReadContestsData, ContestsReadContestsResponse, ContestsCreateContestData, ContestsCreateContestResponse, ContestsReadAvailableContestsData, ContestsReadAvailableContestsResponse, ContestsReadContestProblemsData, ContestsReadContestProblemsResponse, ContestsReadContestData, ContestsReadContestResponse, ContestsUpdateContestData, ContestsUpdateContestResponse, ContestsDeleteContestData, ContestsDeleteContestResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProblemsReadProblemsData, ProblemsReadProblemsResponse, ProblemsCreateProblemData, ProblemsCreateProblemResponse, ProblemsReadProblemData, ProblemsReadProblemResponse, ProblemsUpdateProblemData, ProblemsUpdateProblemResponse, ProblemsDeleteProblemData, ProblemsDeleteProblemResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ContestProblemsService {
    /**
     * Create Contest Problems
     * Create new ContestProblems.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ContestProblemsPublic Successful Response
     * @throws ApiError
     */
    public static createContestProblems(data: ContestProblemsCreateContestProblemsData): CancelablePromise<ContestProblemsCreateContestProblemsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/contest_problems/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Contest Problems
     * Update an ContestProblems.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ContestProblemsPublic Successful Response
     * @throws ApiError
     */
    public static updateContestProblems(data: ContestProblemsUpdateContestProblemsData): CancelablePromise<ContestProblemsUpdateContestProblemsResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/contest_problems/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Contest Problems
     * Delete an ContestProblems.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteContestProblems(data: ContestProblemsDeleteContestProblemsData): CancelablePromise<ContestProblemsDeleteContestProblemsResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/contest_problems/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ContestsService {
    /**
     * Read Contests
     * Retrieve Contests.
     * @param data The data for the request.
     * @param data.status
     * @param data.skip
     * @param data.limit
     * @returns ContestsPublic Successful Response
     * @throws ApiError
     */
    public static readContests(data: ContestsReadContestsData = {}): CancelablePromise<ContestsReadContestsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/contests/',
            query: {
                status: data.status,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Contest
     * Create new Contest.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ContestPublic Successful Response
     * @throws ApiError
     */
    public static createContest(data: ContestsCreateContestData): CancelablePromise<ContestsCreateContestResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/contests/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Available Contests
     * Retrieve contests that may become visible to regular users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ContestSummariesPublic Successful Response
     * @throws ApiError
     */
    public static readAvailableContests(data: ContestsReadAvailableContestsData = {}): CancelablePromise<ContestsReadAvailableContestsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/contests/available',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Contest Problems
     * Retrieve problems for an ongoing contest.
     * @param data The data for the request.
     * @param data.id
     * @returns ContestProblemsListPublic Successful Response
     * @throws ApiError
     */
    public static readContestProblems(data: ContestsReadContestProblemsData): CancelablePromise<ContestsReadContestProblemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/contests/{id}/problems',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Contest
     * Get Contest by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ContestPublic Successful Response
     * @throws ApiError
     */
    public static readContest(data: ContestsReadContestData): CancelablePromise<ContestsReadContestResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/contests/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Contest
     * Update an Contest.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ContestPublic Successful Response
     * @throws ApiError
     */
    public static updateContest(data: ContestsUpdateContestData): CancelablePromise<ContestsUpdateContestResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/contests/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Contest
     * Delete an Contest.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteContest(data: ContestsDeleteContestData): CancelablePromise<ContestsDeleteContestResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/contests/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProblemsService {
    /**
     * Read Problems
     * Retrieve Problems.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ProblemsPublic Successful Response
     * @throws ApiError
     */
    public static readProblems(data: ProblemsReadProblemsData = {}): CancelablePromise<ProblemsReadProblemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/problems/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Problem
     * Create new Problem.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProblemPublic Successful Response
     * @throws ApiError
     */
    public static createProblem(data: ProblemsCreateProblemData): CancelablePromise<ProblemsCreateProblemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/problems/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Problem
     * Get Problem by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ProblemPublic Successful Response
     * @throws ApiError
     */
    public static readProblem(data: ProblemsReadProblemData): CancelablePromise<ProblemsReadProblemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/problems/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Problem
     * Update an Problem.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ProblemPublic Successful Response
     * @throws ApiError
     */
    public static updateProblem(data: ProblemsUpdateProblemData): CancelablePromise<ProblemsUpdateProblemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/problems/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Problem
     * Delete an Problem.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteProblem(data: ProblemsDeleteProblemData): CancelablePromise<ProblemsDeleteProblemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/problems/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}