// This file is auto-generated by @hey-api/openapi-ts

export type AIBattleCreate = {
    contest_id?: (string | null);
    user_submission_id: string;
    models: Array<(string)>;
};

export type AIBattleGeneratedCodeCreate = {
    participant_id: string;
    model_id: string;
    source_code: string;
    finish_reason?: (string | null);
    usage?: ({
    [key: string]: unknown;
} | null);
};

export type AIBattleParticipantPublic = {
    id: string;
    battle_id: string;
    participant_type: string;
    display_name: string;
    model_id?: (string | null);
    submission_id?: (string | null);
    generation_status?: (string | null);
    generation_error?: (string | null);
    order_num: number;
};

export type AIBattlePublic = {
    id: string;
    user_id: string;
    problem_id: string;
    contest_id?: (string | null);
    user_submission_id: string;
    status: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    participants?: Array<AIBattleParticipantPublic>;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContestCreate = {
    title: string;
    start_at: (string | null);
    end_at: (string | null);
};

export type ContestProblemsCreate = {
    problem_id: string;
    contest_id: string;
    order_num?: number;
};

export type ContestProblemsListPublic = {
    data: Array<ContestProblemsPublic>;
    count: number;
};

export type ContestProblemsPublic = {
    problem_id: string;
    contest_id: string;
    order_num?: number;
    id: string;
    problem?: (ProblemMinimal | null);
};

export type ContestProblemsUpdate = {
    problem_id: string;
    contest_id: string;
    order_num?: number;
};

export type ContestPublic = {
    title: string;
    start_at: (string | null);
    end_at: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    problem_links?: Array<ContestProblemsPublic>;
};

export type ContestsPublic = {
    data: Array<ContestPublic>;
    count: number;
};

export type ContestSummariesPublic = {
    data: Array<ContestSummaryPublic>;
    count: number;
    server_now: string;
};

export type ContestSummaryPublic = {
    id: string;
    title: string;
    start_at: string;
    end_at: string;
};

export type ContestUpdate = {
    title: string;
    start_at: (string | null);
    end_at: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type PrivateUserCreate = {
    login_id: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProblemCreate = {
    name: string;
    time_limit: number;
    memory_limit: number;
    content: string;
    input_format: string;
    output_format: string;
    samples: Array<TestCaseSample>;
};

export type ProblemMinimal = {
    id: string;
    name: string;
    time_limit: number;
    memory_limit: number;
};

export type ProblemPublic = {
    name: string;
    time_limit: number;
    memory_limit: number;
    content: string;
    input_format: string;
    output_format: string;
    id: string;
    samples: Array<TestCaseSample>;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProblemsPublic = {
    data: Array<ProblemPublic>;
    count: number;
};

export type ProblemUpdate = {
    name?: (string | null);
    time_limit?: (number | null);
    memory_limit?: (number | null);
    content?: (string | null);
    input_format?: (string | null);
    output_format?: (string | null);
    samples?: (Array<TestCaseSample> | null);
};

export type SubmissionCaseResultPublic = {
    id: string;
    case_index: number;
    verdict: string;
    time_ms?: (number | null);
    memory_kb?: (number | null);
    stdout_preview?: (string | null);
    stderr_preview?: (string | null);
    build_stderr_preview?: (string | null);
    exit_code?: (number | null);
    created_at?: (string | null);
};

export type SubmissionCreate = {
    language: string;
    source_code: string;
    contest_id?: (string | null);
};

export type SubmissionPublic = {
    id: string;
    user_id?: (string | null);
    problem_id: string;
    contest_id?: (string | null);
    participant_type: string;
    ai_model?: (string | null);
    language: string;
    source_code: string;
    verdict: string;
    total_time_ms?: (number | null);
    peak_memory_kb?: (number | null);
    code_bytes?: (number | null);
    physical_lines?: (number | null);
    effective_lines?: (number | null);
    max_nesting_depth?: (number | null);
    analysis_error?: (string | null);
    created_at?: (string | null);
    case_results?: Array<SubmissionCaseResultPublic>;
};

export type SubmissionsPublic = {
    data: Array<SubmissionPublic>;
    count: number;
};

export type TestCaseSample = {
    input: string;
    output: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnlockStatusPublic = {
    problem_id: string;
    ac_count: number;
    unlocked: boolean;
};

export type UserCreate = {
    login_id: string;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    login_id: string;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    login_id: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    login_id?: (string | null);
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AiBattlesCreateAiBattleData = {
    problemId: string;
    requestBody: AIBattleCreate;
};

export type AiBattlesCreateAiBattleResponse = (AIBattlePublic);

export type AiBattlesReadAiBattleData = {
    battleId: string;
};

export type AiBattlesReadAiBattleResponse = (AIBattlePublic);

export type AiBattlesSaveGeneratedCodeData = {
    battleId: string;
    requestBody: AIBattleGeneratedCodeCreate;
};

export type AiBattlesSaveGeneratedCodeResponse = (AIBattleParticipantPublic);

export type ContestProblemsCreateContestProblemsData = {
    requestBody: ContestProblemsCreate;
};

export type ContestProblemsCreateContestProblemsResponse = (ContestProblemsPublic);

export type ContestProblemsUpdateContestProblemsData = {
    id: string;
    requestBody: ContestProblemsUpdate;
};

export type ContestProblemsUpdateContestProblemsResponse = (ContestProblemsPublic);

export type ContestProblemsDeleteContestProblemsData = {
    id: string;
};

export type ContestProblemsDeleteContestProblemsResponse = (Message);

export type ContestsReadContestsData = {
    limit?: number;
    skip?: number;
    status?: (string | null);
};

export type ContestsReadContestsResponse = (ContestsPublic);

export type ContestsCreateContestData = {
    requestBody: ContestCreate;
};

export type ContestsCreateContestResponse = (ContestPublic);

export type ContestsReadAvailableContestsData = {
    limit?: number;
    skip?: number;
};

export type ContestsReadAvailableContestsResponse = (ContestSummariesPublic);

export type ContestsReadContestProblemsData = {
    id: string;
};

export type ContestsReadContestProblemsResponse = (ContestProblemsListPublic);

export type ContestsReadContestData = {
    id: string;
};

export type ContestsReadContestResponse = (ContestPublic);

export type ContestsUpdateContestData = {
    id: string;
    requestBody: ContestUpdate;
};

export type ContestsUpdateContestResponse = (ContestPublic);

export type ContestsDeleteContestData = {
    id: string;
};

export type ContestsDeleteContestResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProblemsReadProblemsData = {
    limit?: number;
    skip?: number;
};

export type ProblemsReadProblemsResponse = (ProblemsPublic);

export type ProblemsCreateProblemData = {
    requestBody: ProblemCreate;
};

export type ProblemsCreateProblemResponse = (ProblemPublic);

export type ProblemsReadProblemData = {
    id: string;
};

export type ProblemsReadProblemResponse = (ProblemPublic);

export type ProblemsUpdateProblemData = {
    id: string;
    requestBody: ProblemUpdate;
};

export type ProblemsUpdateProblemResponse = (ProblemPublic);

export type ProblemsDeleteProblemData = {
    id: string;
};

export type ProblemsDeleteProblemResponse = (Message);

export type SubmissionsCreateSubmissionData = {
    problemId: string;
    requestBody: SubmissionCreate;
};

export type SubmissionsCreateSubmissionResponse = (SubmissionPublic);

export type SubmissionsReadMyProblemSubmissionsData = {
    limit?: number;
    problemId: string;
    skip?: number;
};

export type SubmissionsReadMyProblemSubmissionsResponse = (SubmissionsPublic);

export type SubmissionsReadSubmissionData = {
    submissionId: string;
};

export type SubmissionsReadSubmissionResponse = (SubmissionPublic);

export type SubmissionsReadUnlockStatusData = {
    problemId: string;
};

export type SubmissionsReadUnlockStatusResponse = (UnlockStatusPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);